service: retail
runtime: nodejs20
instance_class: F2
env: standard
entrypoint: npm start


env_variables:
  AUTH0_DOMAIN: "retail-tech.us.auth0.com"
  AUTH0_CLIENT_ID: "n9I94AZIJcNyUf1eYAv2vR1vRyIy0jbm"
  AUTH0_CLIENT_SECRET: "PfHDMz83-11xJauf9wKVslW182cDdHJKy9Api9li5bwlhcGuKtBiMjmUJRSh6-lD"
  AUTH0_CALLBACK_URL: "https://retail-dot-optimus-lnu.df.r.appspot.com//login" 
  

handlers:
  # Serve all static files from the build/static directory
  - url: /static/(.*)
    secure: always 
    static_files: build/static/\1
    upload: build/static/.*

  # Serve files from the root directory
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg)$

  # Serve the React app's index.html for all other routes
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always